application:
  build: docker/application
  links:
    - memcached
  volumes:
    - ./code:/var/www

nginx:
  build: docker/nginx
  ports:
    - "8080:80"
  links:
    - php
  volumes_from:
    - application

memcached:
  image: memcached
  command: memcached -m 128

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=hotflo
    - MYSQL_DATABASE=hotflo
  volumes:
    - ./mysql:/var/lib/mysql

mongo:
  image: mongo:2.6
  volumes:
    - ./mongo:/data/db
 
php:
  build: docker/php-fpm
  working_dir: /var/www
  links:
    - memcached
    - mysql
    - mongo
  volumes_from:
    - application
